languageCode = "en"
languageName = "English"
weight = 1
title = "Naufal Abrar Afifi"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A powerful, lightweight theme for Hugo."

[params.author]
  name = "Naufal Abrar Afifi"
  email = "afifiabrar778@gmail.com"
  image = "img/blowfish_logo.png"
  headline = "Computer Engineering Student at PENS."
  bio = "Pragmatic tech enthusiast focusing on System Optimization, Linux, and Automation."
  links = [
   { github = "https://github.com/nauraafii" },
  ]